"""empty message

Revision ID: 18b855110fe4
Revises: 53f1a1a14300
Create Date: 2019-11-13 13:57:24.994852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18b855110fe4'
down_revision = '53f1a1a14300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('story_ibfk_1', 'story', type_='foreignkey')
    op.drop_constraint('story_ibfk_2', 'story', type_='foreignkey')
    op.create_foreign_key(None, 'story', 'user_info', ['author'], ['id'])
    op.drop_column('story', 'user_id')
    op.drop_index('ix_user_info_user_id', table_name='user_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_info_user_id', 'user_info', ['user_id'], unique=False)
    op.add_column('story', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'story', type_='foreignkey')
    op.create_foreign_key('story_ibfk_2', 'story', 'user', ['user_id'], ['id'])
    op.create_foreign_key('story_ibfk_1', 'story', 'user', ['author'], ['id'])
    # ### end Alembic commands ###
