"""empty message

Revision ID: 53f1a1a14300
Revises: dfce9567d13c
Create Date: 2019-11-13 11:42:45.038722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f1a1a14300'
down_revision = 'dfce9567d13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_info_user_id'), 'user_info', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_info_user_id'), table_name='user_info')
    # ### end Alembic commands ###
