"""empty message

Revision ID: dfce9567d13c
Revises: 
Create Date: 2019-11-13 11:38:10.243284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfce9567d13c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('video', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.String(length=100), nullable=False),
    sa.Column('times', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iphone', sa.String(length=11), nullable=True),
    sa.Column('pwd', sa.String(length=32), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('times', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iphone')
    )
    op.create_table('friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('f_age', sa.String(length=2), nullable=True),
    sa.Column('f_high', sa.String(length=3), nullable=True),
    sa.Column('f_education', sa.String(length=2), nullable=True),
    sa.Column('f_income', sa.String(length=1), nullable=True),
    sa.Column('f_register', sa.String(length=30), nullable=True),
    sa.Column('f_residence', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('desc', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('times', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.Enum('m', 'n'), nullable=True),
    sa.Column('birth', sa.DateTime(), nullable=True),
    sa.Column('age', sa.String(length=2), nullable=True),
    sa.Column('high', sa.String(length=3), nullable=False),
    sa.Column('education', sa.String(length=2), nullable=False),
    sa.Column('profession', sa.String(length=20), nullable=False),
    sa.Column('income', sa.String(length=1), nullable=True),
    sa.Column('property', sa.String(length=50), nullable=False),
    sa.Column('residence', sa.String(length=30), nullable=False),
    sa.Column('register', sa.String(length=30), nullable=False),
    sa.Column('qq', sa.String(length=20), nullable=True),
    sa.Column('wechat', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('qq'),
    sa.UniqueConstraint('wechat')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    op.drop_table('story')
    op.drop_table('friend')
    op.drop_table('user')
    op.drop_table('class')
    # ### end Alembic commands ###
